on: [push]

jobs:
  python_pre_commit:
    name: Run pre-commit
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python: ['3.8.8']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          architecture: 'x64'

      - name: Run pre-commit commands
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -U pip wheel
          pip install -r requirements.txt
          pre-commit run --all-files
