name: Windows build

on: push

jobs:
  build-pyinstaller:
    name: Build Streamlit app with PyInstaller
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files
        run: ls
  
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.8'
          architecture: 'x64'

      - run: python --version
      - run: python -m venv venv
      - run: .\venv\Scripts\Activate.ps1
      - run: pip install -r windows-requirements.txt
      - run: cd build && ./build.ps1
      - run: ls build
      - run: ls build/dist
      - run: 7z a -r -tzip mosaic-streamlit-windows.zip build/dist/run
        
      - uses: actions/upload-artifact@v2
        with:
          name: mosaic-streamlit-windows.zip
          path: mosaic-streamlit-windows.zip

